export const dataDentist = [
  {
    id: '1',
    name: 'John Doe',
    phone: '+1234567890',
    mail: 'john.doe@example.com',
    birthday: '1990-05-15',
  },
  {
    id: '2',
    name: 'Jane Smith',
    phone: '+1987654321',
    mail: 'jane.smith@example.com',
    birthday: '1985-12-10',
  },
  {
    id: '3',
    name: 'Michael Johnson',
    phone: '+14445556666',
    mail: 'michael.johnson@example.com',
    birthday: '1982-08-25',
  },
  {
    id: '4',
    name: 'Emily Brown',
    phone: '+17778889999',
    mail: 'emily.brown@example.com',
    birthday: '1995-03-20',
  },
  {
    id: '5',
    name: 'David Wilson',
    phone: '+16504321098',
    mail: 'david.wilson@example.com',
    birthday: '1987-06-12',
  },
  {
    id: '6',
    name: 'Sarah Lee',
    phone: '+15551234987',
    mail: 'sarah.lee@example.com',
    birthday: '1991-09-30',
  },
  {
    id: '7',
    name: 'Robert Garcia',
    phone: '+18887776655',
    mail: 'robert.garcia@example.com',
    birthday: '1980-11-05',
  },
  {
    id: '8',
    name: 'Maria Martinez',
    phone: '+16669998877',
    mail: 'maria.martinez@example.com',
    birthday: '1989-04-18',
  },
  {
    id: '9',
    name: 'Daniel White',
    phone: '+13334445555',
    mail: 'daniel.white@example.com',
    birthday: '1993-07-08',
  },
  {
    id: '10',
    name: 'Jessica Taylor',
    phone: '+17778889900',
    mail: 'jessica.taylor@example.com',
    birthday: '1984-02-15',
  },
];

export const dataDentistDetail = {
  id: '1',
  userDTO: {
    name: 'Michael Johnson',
    phone: '+1122334455',
    mail: 'michael.johnson@example.com',
    role: 'CUSTOMER',
    birthday: '1980-03-28',
  },
  appointment: [
    {
      appointmentID: '4',
      status: 0,
      date: '2024-07-10',
      feedback: 'sastdraisdn',
      dentistScheduleId: 'DS004',
      dependent: {
        dependentID: 'string',
        name: '',
        birthday: '2024-06-24',
        user: {
          userID: 'string',
          name: 'string',
          phone: 'string',
          mail: 'string',
          password: 'string',
          role: 'CUSTOMER',
          birthday: '2024-06-24',
          status: 0,
          enabled: true,
          username: 'string',
          authorities: [
            {
              authority: 'string',
            },
          ],
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
        },
        dependentList: ['string'],
      },
      staff: {
        staffID: 'ST003',
        user: {
          userID: 'USR006',
          name: 'Dr. Anderson',
          phone: '+7654321098',
          mail: 'dr.anderson@example.com',
          password: 'password',
          role: 'DENTIST',
          birthday: '1982-09-15',
          status: 1,
          enabled: true,
          username: 'dranderson',
          authorities: [
            {
              authority: 'ROLE_DENTIST',
            },
          ],
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
        },
        clinic: {
          clinicID: 'CL005',
          name: 'Gentle Dental Care',
          phone: '+9876543210',
          address: '678 Elm Street, Riverdale',
          slotDuration: {
            hour: 0,
            minute: 45,
            second: 0,
            nano: 0,
          },
          openTime: {
            hour: 9,
            minute: 0,
            second: 0,
            nano: 0,
          },
          closeTime: {
            hour: 17,
            minute: 0,
            second: 0,
            nano: 0,
          },
          breakStartTime: {
            hour: 12,
            minute: 0,
            second: 0,
            nano: 0,
          },
          breakEndTime: {
            hour: 13,
            minute: 0,
            second: 0,
            nano: 0,
          },
          status: 1,
        },
      },
      user: {
        userID: 'USR007',
        name: 'Michael Johnson',
        phone: '+1122334455',
        mail: 'michael.johnson@example.com',
        password: 'password',
        role: 'CUSTOMER',
        birthday: '1980-03-28',
        status: 1,
        enabled: true,
        username: 'michaelj',
        authorities: [
          {
            authority: 'ROLE_CUSTOMER',
          },
        ],
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
      },
      timeSlot: {
        timeSlotID: 'TS003',
        slotNumber: 3,
        startTime: {
          hour: 15,
          minute: 0,
          second: 0,
          nano: 0,
        },
      },
      dentist: {
        dentistID: 'DNT003',
        user: {
          userID: 'USR006',
          name: 'Dr. Anderson',
          phone: '+7654321098',
          mail: 'dr.anderson@example.com',
          password: 'password',
          role: 'DENTIST',
          birthday: '1982-09-15',
          status: 1,
          enabled: true,
          username: 'dranderson',
          authorities: [
            {
              authority: 'ROLE_DENTIST',
            },
          ],
          accountNonExpired: true,
          accountNonLocked: true,
          credentialsNonExpired: true,
        },
      },
      services: {
        serviceID: 'SRV003',
        name: 'Tooth Extraction',
      },
      clinic: {
        clinicID: 'CL006',
        name: 'Smile Bright Clinic',
        phone: '+6543210987',
        address: '789 Cedar Avenue, Hilltop',
        slotDuration: {
          hour: 0,
          minute: 30,
          second: 0,
          nano: 0,
        },
        openTime: {
          hour: 8,
          minute: 0,
          second: 0,
          nano: 0,
        },
        closeTime: {
          hour: 16,
          minute: 30,
          second: 0,
          nano: 0,
        },
        breakStartTime: {
          hour: 12,
          minute: 30,
          second: 0,
          nano: 0,
        },
        breakEndTime: {
          hour: 13,
          minute: 30,
          second: 0,
          nano: 0,
        },
        status: 1,
      },
    },
  ],
};

export const dashboardData = {
  dailyAppointments: {
    'UserDTO(id=tan, name=strings, phone=997264564, mail=dentist3, birthday=2024-06-19)': 1,
    'UserDTO(id=khoa, name=strings2, phone=197264564, mail=dentist4, birthday=2024-06-19)': 2,
  },
  monthlyAppointments: {
    6: 1,
    7: 1,
  },
  totalAppointmentsInMonthNow: 1,
  totalAppointmentsInYearNow: 3,
};
export const appointmentData = {  
  appointmentId: "4ae0527e-b344-4c72-9367-4e6ffc767c5e",
  status: 1,
  date: "2024-06-19",
  staff: "example1",
  user: "example1",
  dependent: null,
  timeSlot: "07:00:00",
  dentist: "strings",
  services: "Tooth Extraction",
  clinic: null
}
