spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dentistrysunflower@gmail.com
    password: hjmewqpnqgnobvcq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

secret_key:
  hs256: b1b61a49c7ad56cc29e71343a2fbbed93e0d459c3ac7949dd39f401236fd87d9

app:
  cors:
    allowed-origins: http://localhost:3000
