spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=DentistryBookingSystem;encrypt=false
    username: sa
    password: 123
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: phucnhse183026@fpt.edu.vn
    password: yjyufsdhiuwxndkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

secret_key:
  hs256: b1b61a49c7ad56cc29e71343a2fbbed93e0d459c3ac7949dd39f401236fd87d9