spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DentistryManagementSystem
    username: product_user
    password: product_user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dentistrysunflower@gmail.com
    password: hjmewqpnqgnobvcq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  confirmation:
    link:
      baseurl: http://localhost:8080
  data:
    redis:
      url: redis://default:9YPndKjEv7ZQjaHLvgUaq3LQAIYSelBd@redis-18190.c1.asia-northeast1-1.gce.redns.redis-cloud.com:18190

  profiles:
    default: default

application:
  security:
    jwt:
      secret-key:
        hs256: b1b61a49c7ad56cc29e71343a2fbbed93e0d459c3ac7949dd39f401236fd87d9
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

