spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
  datasource:
    url: jdbc:mysql:///DentistryManagementSystem?cloudSqlInstance={INSTANCE_ID}:{REGION}:sunflowerdentistry&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: sa
    password: Haha123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dentistrysunflower@gmail.com
    password: hjmewqpnqgnobvcq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  confirmation:
    link:
      baseurl: http://localhost:8080
  cloud:
    gcp:
      sql:
        database-name: DentistryManagementSystem
        instance-connection-name: {INSTANCE_ID}
  data:
    redis:
      url: {REDIS_URL}
application:
  security:
    jwt:
      secret-key:
        hs256: {SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
